Description of ASK_site_init
ASK_site_init
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ASK_read_asklut ASK_READ_ASKLUT - reads ASK meta-datafrom look up tables
ASK_site_setup at lora.phys.soton.ac.uk: videodir = '/stp/raid2/ask/data'; % Here it is OK to have!
This function is called by:
ASK_read_vs ASK_READ_VS - the procedure to read the videoevent setup - the new version
SOURCE CODE
ASK_site_setup
% TODO: move this one out of here, this is an initialization call,
% not a set-up, shouldn't be here!
% * step 1: find out where it the script is called and change that
%   to ASK_site_setup, ASK_site_init or some such
% * step 2: then put this line into the ASK_site_init.m
ASK_read_asklut(ASKLUTfile);
% * step 3 move the other hard-coded set-ups into this and this
%   script into these places.