function [SkMp] = skymap(pos,time,SkMp)
% SKYMAP An easy to use astronomical starchart.
% It sets up a graphical user ingerface for the skymap and an input
% figure for selection of observation sites, date and time. The
% default star catalog is the Bright Star Catalog, in addition
% skymap is coupled to the Pulkovo Spectrophotometric Catalog and
% allows extraction of the stellar spectra of the stars in that
% catalog. Skymap can also interface with the PlanetsPos_package to
% get the position of the Moon and the planets.
%
% Calling:
%   SkMp = skymap(pos,time,SkMp);
% Input:
%   pos - longitude and latitude of position (degrees), double
%         array [long lat], optional argument, dafaults to first
%         location in station-list as defined in Xephem.stations in
%         the Stations sub-directory.
%   time - UTC-time to display, [yyyy mm dd HH MM SS], double
%          array, optional input argument, defaults to current time
%          as returned by the now-command.
%  SkMp  - SkMp-struct as returned by skymap, optional input
%          argument, not too useful for user-use.
% Output:
%  SkMp - struct holding all star-catalog variable and the
%         GUI-ui-handles etc. a variable with the literal name SkMp
%         will be created (this skymap-program is very old and this
%         was at the time the easiest way to do this.)
% 
% Example:
%  SkMp = skymap;
%  % Select or specify the location and time of observatiop. The
%  % graphical user-interface should be reasonably self-explanatory.
% 
% See also: PlanetPos (https://se.mathworks.com/matlabcentral/fileexchange/77359-positions-of-solar-system-bodies)
% 

%   Copyright © 20200918 Bjorn Gustavsson, <bjorn.gustavsson@uit.no>
%   This is free software, licensed under GNU GPL version 2 or later
%
%   Copyright © 20200918 Bjorn Gustavsson, <bjorn.gustavsson@irf.se>
%   This is free software, licensed under GNU GPL version 2 or later
%
%   Copyright © 20010401 Bjorn Gustavsson, <bjorn.gustavsson@irf.se>
%   This is free software, licensed under GNU GPL version 2 or later


verstr = version;
version_nr = str2double(verstr(1:3));


stardir = fileparts(which('skymap'));

checkokstr = '[stnnames,SkMp] = checkok(SkMp);';
updstrplstr = '[SkMp] = updstrpl(SkMp);';
str0 =  ['SkMp.radecl_or_azze = 0;',updstrplstr];
str1 = ['SkMp.radecl_or_azze = 1;',updstrplstr];

SkMp.set_up_file = fullfile(stardir,'set_up_file.dat');
SkMp.radecl_or_azze = 1;

if nargin < 3
  SkMp.optpar = [];
  SkMp.img = [];
  SkMp.identstars = [];
end
%         alts
[long,lat,  ~ ,StnNames,stnNR] = station_reader;
% $$$ Cannot completely remove Pelle and Kalle, can I?
% $$$ Nope, They'll remain as characters in this script for as long as I live!
% $$$ load(fullfile(stardir,'Stations','stationpos.dat'))
% $$$ pelle = stationpos(:,4).*(stationpos(:,1) + stationpos(:,2)/60 + stationpos(:,3)/3600);
% $$$ if abs(stationpos(:,8)) == 1
% $$$   kalle = stationpos(:,8).*(stationpos(:,5) + stationpos(:,6)/60 + stationpos(:,7)/3600);
% $$$ else
% $$$   kalle = (stationpos(:,5) + stationpos(:,6)/60 + stationpos(:,7)/3600);
% $$$ end
% $$$ stationpos = [kalle,pelle];
SkMp.stationpos = [long,lat];
SkMp.longlat = [long,lat];
SkMp.StnNames = StnNames;
SkMp.stnNR = stnNR;
SkMp.figchok = [];

if ~isfield(SkMp,'prefs')
   SkMp = def_s_preferences(SkMp);
end

try 
  Mon_Pos = get(0,'MonitorPositions');
catch
  Mon_Pos = [0 0 700 700];
end

SkMp.figsky = figure('Name','Skyview',...
		     'Position',[Mon_Pos(3)-600,Mon_Pos(4)-600,540,530],...
		     'Resize','on',...
		     'MenuBar','none');
set(SkMp.figsky,'color',SkMp.prefs.pl_cl_bg)

figure(SkMp.figsky);
% The slider on the left edge
SkMp.ui3(1) = uicontrol('Units','normalized',...
			'Style','Slider',...
			'Position',[.01,.1,.03,.8],...
			'Min',-90,...
			'Max',90,...
			'Value',0,...
			'Sliderstep',[0.003,0.05],...
			'Callback',updstrplstr);
% The slider on the right edge
SkMp.ui3(2) = uicontrol('Units','normalized',...
			'Style','Slider',...
			'Position',[.96,.1,.03,.8],...
			'Min',-180,...
			'Max',180,...
			'Value',0,...
			'Sliderstep',[0.003,0.05],...
			'Callback',updstrplstr);
% The slider on the lower edge
SkMp.ui3(3) = uicontrol('Units','normalized',...
			'Style','Slider',...
			'Position',[.1,.01,.8,.03],...
			'Min',-90,...
			'Max',90,...
			'Value',0,...
			'Sliderstep',[0.003,0.05],...
			'Callback',updstrplstr);
% The slider on the upper edge. 
SkMp.ui3(4) = uicontrol('Units','normalized',...
			'Style','Slider',...
			'Position',[.1,.96,.8,.03],...
			'Min',0,...
			'Max',100,...
			'Value',45,...
			'Sliderstep',[0.003,0.05],...
			'Callback',updstrplstr);
% Pop-up menu for star magnitudes:
SkMp.ui3(5) = uicontrol('Units','normalized',...
			'Style','Popup',...
			'String','magn|2|2.5|3|3.5|4|4.5|5|5.5|6|6.5|7|7.5|8|8.5|9|9.5',...
			'Position',[.01,.94,.075,.05],...
			'Min',-180,...
			'Max',180,...
			'Value',8,...
			'Callback',updstrplstr);
% Uimenues:
SkMp.uic3(1,1) = uimenu('Label','File');
SkMp.uic3(1,2) = uimenu(SkMp.uic3(1,1),...
			'Label','Figure',...
			'Callback','figure',...
			'position',1);
SkMp.uic3(1,3) = uimenu(SkMp.uic3(1,1),...
			'Label','Close',...
			'Callback','skmp_close',...
			'position',2);
SkMp.uic3(1,4) = uimenu(SkMp.uic3(1,1),...
			'Label','Page setup',...
			'Callback','pagesetupdlg',...
			'position',3);
SkMp.uic3(1,5) = uimenu(SkMp.uic3(1,1),...
			'Label','Print',...
			'Callback','printdlg',...
			'position',4);
SkMp.uic3(1,6) = uimenu(SkMp.uic3(1,1),...
			'Label','Preferences',...
			'position',5);
SkMp.uic3(1,7) = uimenu(SkMp.uic3(1,6),...
			'Label','Default',...
			'Callback','SkMp = s_preferences(SkMp,0);');
SkMp.uic3(1,7) = uimenu(SkMp.uic3(1,6),...
			'Label','Plot',...
			'Callback','SkMp = s_preferences(SkMp,2);');
SkMp.uic3(1,8) = uimenu(SkMp.uic3(1,6),...
			'Label','Plot color',...
			'Callback','SkMp = s_preferences(SkMp,3);');
SkMp.uic3(1,9) = uimenu(SkMp.uic3(1,6),...
			'Label','Plot sizes',...
			'Callback','SkMp = s_preferences(SkMp,4);');
SkMp.uic3(1,9) = uimenu(SkMp.uic3(1,6),...
			'Label','Change background',...
			'Callback','SkMp = s_preferences(SkMp,6);');

SkMp.uic3(2,1) = uimenu('Label','Pos/time');
SkMp.uic3(2,2) = uimenu(SkMp.uic3(2,1),...
			'Label','Display Pos/time',...
			'Callback','skmp_disp_pos_time(SkMp)');
SkMp.uic3(2,3) = uimenu(SkMp.uic3(2,1),...
			'Label','New Pos/time',...
			'Callback',checkokstr);
SkMp.uic3(3,1) = uimenu('Label','Star');
SkMp.uic3(3,2) = uimenu(SkMp.uic3(3,1),...
			'Label','Inform',...
			'Callback','[SkMp,staraz,starze,starid,starmagn,thisstar] = updstrinfo(SkMp);');
SkMp.uic3(3,3) = uimenu(SkMp.uic3(3,1),'Label','Plot star spectra','Callback','[ph,SkMp]=plotspec(SkMp);');
SkMp.uic3(3,4) = uimenu(SkMp.uic3(3,1),'Label','assign star spectra','Callback','guigetspec(SkMp)');
SkMp.uic3(3,5) = uimenu(SkMp.uic3(3,1),'Label','Ra/decl','Callback',str0);
SkMp.uic3(3,6) = uimenu(SkMp.uic3(3,1),'Label','Azim/Zen','Callback',str1);
SkMp.uic3(3,7) = uimenu(SkMp.uic3(3,1),'Label','Find by name','Callback','updfindwname(SkMp)');
SkMp.uic3(5,1) = uimenu('Label','Favourites');
SkMp.uic3(5,1) = uimenu('Label','Favourites');
try
  % Try to read file Favourites.txt and build the Favourites menu from that
  Ffid = fopen('Favourites.txt','r');
  B = textscan(Ffid,'%s');
  fclose(Ffid);
  B = B{1};
  for i1 = 1:numel(B)
    callbackstr = ['skmp_plot_named(SkMp,''',B{i1},''');'];
    SkMp.uic3(5,i1+1) = uimenu(SkMp.uic3(5,1),...
      	    		'Label',B{i1},...
	    		    'Callback',callbackstr);
  end
catch
  % If that fails just make a default one
  delete(SkMp.uic3(5,2:end))
  SkMp.uic3(5,2) = uimenu(SkMp.uic3(5,1),...
  			'Label','Moon',...
			'Callback','skmp_plot_named(SkMp,''Moon'');');
  SkMp.uic3(5,3) = uimenu(SkMp.uic3(5,1),...
			'Label','Mercury',...
			'Callback','skmp_plot_named(SkMp,''Mercury'');');
  SkMp.uic3(5,4) = uimenu(SkMp.uic3(5,1),...
			'Label','Venus',...
			'Callback','skmp_plot_named(SkMp,''Venus'');');
  SkMp.uic3(5,5) = uimenu(SkMp.uic3(5,1),...
			'Label','Mars',...
			'Callback','skmp_plot_named(SkMp,''Mars'');');
  SkMp.uic3(5,6) = uimenu(SkMp.uic3(5,1),...
			'Label','Jupiter',...
			'Callback','skmp_plot_named(SkMp,''Jupiter'');');
  SkMp.uic3(5,7) = uimenu(SkMp.uic3(5,1),...
			'Label','Saturn',...
			'Callback','skmp_plot_named(SkMp,''Saturn'');');
  SkMp.uic3(5,8) = uimenu(SkMp.uic3(5,1),...
			'Label','Uranus',...
			'Callback','skmp_plot_named(SkMp,''Uranus'');');
  SkMp.uic3(5,9) = uimenu(SkMp.uic3(5,1),...
			'Label','Neptune',...
			'Callback','skmp_plot_named(SkMp,''Neptune'');');
  SkMp.uic3(5,10) = uimenu(SkMp.uic3(5,1),...
			'Label','Capella',...
			'Callback','skmp_plot_named(SkMp,''Capella'');');
  SkMp.uic3(5,11) = uimenu(SkMp.uic3(5,1),...
			'Label','Polaris',...
			'Callback','skmp_plot_named(SkMp,''Polaris'');');
  SkMp.uic3(5,12) = uimenu(SkMp.uic3(5,1),...
			'Label','Vega',...
			'Callback','skmp_plot_named(SkMp,''Vega'');');
end
SkMp.uic3(4,1) = uimenu('Label','Help');
SkMp.uic3(4,2) = uimenu(SkMp.uic3(4,1),...
			'Label','Help',...
			'Callback','skyhelp(5);');
SkMp.uic3(4,3) = uimenu(SkMp.uic3(4,1),...
			'Label','WARRANTY',...
			'Callback','skyhelp(6);');
SkMp.uic3(4,4) = uimenu(SkMp.uic3(4,1),...
			'Label','Copyright',...
			'Callback','skyhelp(7);');
set(SkMp.uic3(3,5),'enable','off')
for i1 = size(SkMp.uic3,1):-1:1
  for i2 = size(SkMp.uic3,2):-1:1
    try
      set(SkMp.uic3(i1,i2),'handlevisibility','callback')
    catch
      % whatever, it was only a placeholder anyways
    end
  end
end
set(SkMp.ui3(:),'handlevisibility','callback')

if ( version_nr > 5.1 )
  
  set(SkMp.ui3(1),'TooltipString','Change NORTH-SOUTH angle');
  set(SkMp.ui3(2),'TooltipString','Change ROLL angle');
  set(SkMp.ui3(3),'TooltipString','Change EAST-WEST angle');
  set(SkMp.ui3(4),'TooltipString','Change FIELD OF VIEW angle');
  set(SkMp.ui3(5),'TooltipString','Change MAGNITUDE OF FAINTEST STAR');
  
else
  
  set(SkMp.uic3(1,4),'Callback','pagedlg')
  
end
if nargin > 1
  
  SkMp.ui815 = [];
  SkMp.tid0 = time;
  SkMp.pos0 = pos;
  [SkMp] = checkisok(SkMp);
  
else
  
  [~,SkMp] = checkok(SkMp);
  
end

% if nargout == 0
  
  assignin('base','SkMp',SkMp)
  
% end
