Description of colorbar_labeled
colorbar_labeled
PURPOSE
COLORBAR_LABELED - colorbar with label for range linear or log
SYNOPSIS
function handle=colorbar_labeled(label,lg,varargin)
DESCRIPTION
 COLORBAR_LABELED - colorbar with label for range linear or log
 scale.
 Calling:
   handle=colorbar_labeled(label,lg)
 Input:
   label - string with text
   lg    - string [ {'linear'} | 'log' ] for scale type
CROSS-REFERENCE INFORMATION
This function calls:
find_in_cellstr FIND_IN_CELLSTR - search for string in cellstrings
This function is called by:
ASK_keogram_overlayed ASK_KEOGRAM_OVERLAYED - to plot an overlayed keogram, ASK images, and
ASK_play_keolines2 ASK_PLAY_KEOLINES -
askChem2em_TAVplot ASKCHEM2EM_AVPLOT - plot time-altitude variation of emission rates
density_plotter Scaffolding/pattern for plotting density outputs from the
sotonChem2em_TAVplot sotonChem2em_TAVplot - plot time-altitude variation of emission rates
sotonICdensity_plotter Scaffolding/pattern for plotting density outputs from the
flamingraysnapshot
flamingraysnapshot2
runner4FlamingRayParSequence % Run the core set-up tasks first
runner4FlamingRaySequence % Run the core set-up tasks first
runner4FlamingRays0 % Example script: how to estimate electron energies in flaming rays
runner4FlamingRaysAVGx0y0NarrowerE % Run all set-up tasks first
runner4FlamingRaysAVGx0y0WideningE % Run all set-up tasks first
runner4FlamingRaysTOWARDSx0y0NarrowerE % Run the core set-up tasks first
runner4FlamingRaysTOWARDSx0y0WideningE % Run the core set-up tasks first
runner4FlamingRaysTOWARDSx0y0WideningE2 % Run the core set-up tasks first
runnerWithPanic % Run the core set-up tasks first
starter4FlamingRay % Example script: how to estimate electron energies in flaming rays
starter4FlamingRayE % Example script: how to estimate electron energies in flaming rays
starter4PointsOverImgE % Example script: how to estimate electron energies in flaming rays
aidathumbImTool AIDATHUMBIMTOOL - display image and intensities in centre line and column
img_splinefilter IMG_SPLINEFILTER - spline fitting optimum statistical filter
img_svdfilter IMG_SVDFILTER - SVD fitting filter optimum statistical filter
imgs_plot imgs_plot - Plot a row of images
imgs_plot_bg_red1l imgs_plot_bg_red1l - Plot a row of background reduced images, one colorlabel
imgs_plot_bg_red_clall imgs_plot_bg_red - Plot a row of background reduced images with colorbars
imthumbImTool IMTHUMBIMTOOL - display image and intensities in centre line and column
imthumbImToolupdateRCcuts IMTHUMBIMTOOlUPDATERCCUTS - update line and column intensities cuts
SOURCE CODE
function handle=colorbar_labeled(label,lg,varargin)
% COLORBAR_LABELED - colorbar with label for range linear or log
% scale.
%
% Calling:
%   handle=colorbar_labeled(label,lg)
% Input:
%   label - string with text
%   lg    - string [ {'linear'} | 'log' ] for scale type
if nargin<2 || isempty(lg),
  lg='linear';
end
% Determine color limits by context.  If any axes child is an image
% use scale based on size of colormap, otherwise use current CAXIS.
t=caxis;
h=gca;
% Search for existing colorbar
ch=get(gcf,'children');
ax=[];
try
  for i=1:length(ch),
    d=get(ch(i),'userdata');
    if numel(d)==1 && d==h
      ax=ch(i);
      break
    end
  end
catch
  % Dont know what to do around here...
end
if strcmp(get(gcf,'NextPlot'),'replace'),
  set(gcf,'NextPlot','add')
  wasNextplotReplace = 1;
else
  wasNextplotReplace = 0;
end
if isempty(ax)
  pos=get(h,'Position');
% stripe=0.03; edge=0.08;
% [az,el]=view;
% if all([az,el]==[0 90]), space=0.02; else, space=.1; end
% set(h,'Position',[pos(1) pos(2) pos(3)*(1-stripe-edge-space) pos(4)])
% rect=[pos(1)+(1-stripe-edge)*pos(3) pos(2) stripe*pos(3) pos(4)];
  rect=[pos(1)+1.02*pos(3) pos(2) .035*pos(3) pos(4)];
  % Create axes for stripe
  ax=axes('Position', rect);
else
  axes(ax)
end
if ~isempty(varargin)
  fszi = find_in_cellstr('fontsize',varargin);
  if ~isempty(fszi)
    fsz = varargin{fszi+1}-2;
  else
    fsz = get(gca,'fontsize');
  end
else
  fsz = get(gca,'fontsize');
end
% Create color stripe
cmap = colormap;
n=size(cmap,1);
if strcmp(lg,'log')
  tt=((0:n)-.5)'*diff(t)/(n-1)+t(1);
  surface([0 1],10.^tt,[tt tt]),shading flat
  set(ax,'CLim',t,'ylim',10.^t,'yscale','log','layer','top','fontsize',fsz)
  %surface([0 1],tt,[tt tt]),shading flat
  %set(ax,'CLim',t,'ylim',t,'yscale','log','layer','top','fontsize',fsz)
else
  %image([0 1],t,[1:n]'),
  tt=((0:n)-.5)'*diff(t)/(n-1)+t(1);
  surface([0 1],tt,[tt tt]),shading flat
  set(ax,'CLim',t,'ylim',t,'yscale','linear','layer','top','fontsize',fsz)
% set(ax,'TickDir','in')
  set(ax,'ylim',t,'Ydir','normal')
% Justify color axis
% set(ax,'yticklabel',strjust(get(ax,'yticklabel')))
end
set(ax,'userdata',h,'YaxisLoc','right','xtick',[])
  ylabel(label,'Rotation',-90,'VerticalAlignment','baseline',varargin{:})
% $$$ try
% $$$ catch
% $$$   ylabel(label,'Rotation',-90,'VerticalAlignment','baseline')
% $$$ end
set(gcf,'CurrentAxes',h)
if wasNextplotReplace == 1
  set(gcf,'Nextplot','Replace')
end
if nargout>0,
  handle=ax;
end