#!/bin/bash
#++++++++++++++++
#.IDENTIFICATION getsp
#.LANGUAGE       Bash
#.AUTHOR         Francois Ochsenbein <francois@astro.u-strasbg.fr>
#.ENVIRONMENT    CDS Catalogues Service
#.KEYWORDS       
#.VERSION  1.0   14-Jan-1998: Creation
#.VERSION  1.1   22-Jan-2001: 'echo' command is unusable -- use gawk
#.PURPOSE        Find out the spectrophotometry for a HR star for
#                Catalogue III/201 = Spectrophotometric Pulkovo Catalog
#.COMMENTS       The program accepts the following arguments:
#    Arg#1 (required): HR number
#    Arg#2 (optional): contents of column "table" for the HR number
#                from file "stars.dat"
#----------------

#### Check the number of arguments in the correct range.
if [ "$#" -eq 0 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 HR_number [5|6|a|b]"
    echo "       Print out the spectrophotometry for one star from file(s):"
    echo "       table5.dat table6.dat table5a.dat table[56].dat"
    exit 1
fi

#### Look in stars.dat, search for the table(s) with spectrophotometry
# Assign the first command line argument to hr and then shift
hr="$1"
shift

# Check if there are more arguments left after the shift
if [ $# -gt 0 ]; then
    t="$1"
    shift
else
    f="stars.dat"
    # Use awk to process the file and find the appropriate value for t based on hr
    # This part of the script has been translated to use shell variable substitution correctly
    # Write the output to a temporary file
    tmpfile="/tmp/g$$$.hr"
    awk -v hr="$hr" '{
        hr_val=substr($0,1,4)+0;
        if (hr_val>hr) exit;
        if (hr_val==hr) {t = substr($0,79,1); exit}
        }
        END {if(t=="") t="*"; print t}' "$f" > "$tmpfile"
    t=$(cat "$tmpfile")
    /bin/rm -f "$tmpfile"
fi

#### Transform the "table" column contents into table name(s)
case "$t" in
    5|6)
        file=table$t.dat
        ;;
    a)
        file=table5a.dat
        ;;
    b)
        file="table5.dat table6.dat"
        ;;
    *)
        echo "****Table '$t' can't include star HR '$hr'"
        exit 1
        ;;
esac

#### When called from vizExec, output in latex (htx)
if [ -n "$PATH_INFO" ]; then
    tex=1
else
    tex=0
fi

#### Print the wavelength and flux (Wavelength in col#1, flux in col#k)
for f in $file
do
    cat $f | gawk -v hr="$hr" -v f="$f" -v tex="$tex" -v fg="FireBrick" '
     BEGIN{if (tex>0) { \
      fmt= "\\section{Flux for star {\\fg{%s} HR %s} from file {\\tt %s}}\n";\
      printf(fmt,fg,hr,f); print "\\begin{alltt}\n\\# nm   Flux(W/m2/m)" }\
     else printf("# nm  Flux(W/m2/m) for star HR %s from file: %s\n",hr,f)}\
     END{if(tex>0) print "\\end{alltt}\\hline"; else print ""}\
     /^      /{if(k>1) exit ;\
     for(i=1; i<=NF; i++) { if ((k==0)&&($i=='$hr')) {k=i+1 ;next}}\
      } { if (k>1) printf("%6s %s\n", $1, $k)}' | sed 's/ \./ 0./'
done
#######################################################################