function D = delsqReg(G)
%DELSQ  Construct five-point finite difference Laplacian.
%   delsq(G) is the sparse form of the two-dimensional,
%   5-point discrete negative Laplacian on the grid G.
%   The grid G can be generated by NUMGRID or NESTED.
%
%   See also NUMGRID, DEL2, DELSQDEMO.

%   C. Moler, 7-16-91.
%   Copyright 1984-2002 The MathWorks, Inc. 
%   $Revision: 1.1.6.2 $  $Date: 2010/09/02 13:36:57 $

[m,~] = size(G);

% Indices of interior points
p = find(G);
idxC = G((2:end-1),(2:end-1));
nUp = G((2:end-1)+1,(2:end-1));
nDown = G((2:end-1)-1,(2:end-1));
nLeft = G((2:end-1),(2:end-1)-1);
nRight = G((2:end-1),(2:end-1)+1);
Ipositives = [nUp(:),nDown(:),nLeft(:),nRight(:)];

% Connect interior points to themselves with 4's.
i = G(p);
j = G(p);
% nNeighbours = double((nUp~=0)+(nDown~=0)+(nLeft~=0)+(nRight~=0));
% s = nNeighbours(:);
I1 = [];
I2 = [];
DW = [];
idxRow = 1;
for i1 = 1:numel(idxC)
  if idxC(i1) ~= 0
    iPcurr = Ipositives(i1,Ipositives(i1,:)>0);
    idx1 = [idxRow,idxRow*ones(size(iPcurr))];
    idx2 = [idxC(i1),iPcurr];  % [idxRow, iPcurr]; %            
    Cweight = [-numel(iPcurr),ones(size(iPcurr))];
    if any(idx1 < 0) || any(idx2 < 0)
      dbstop
    end
    I1 = [I1,idx1];
    I2 = [I2,idx2];
    DW = [DW,Cweight];
    idxRow = idxRow + 1;
  end
end
D = sparse(I1,I2,DW);
% s = double((G((2:end-1)+1,(2:end-1)) ~= 0) + ...
%                      (G((2:end-1)-1,(2:end-1)) ~= 0) + ...
%                      (G((2:end-1),(2:end-1)-1) ~= 0) + ...
%                      (G((2:end-1),(2:end-1)+1) ~= 0));
% s = s(:);
% 
% % for k = north, east, south, west
% for k = [-1 m 1 -m]
%    % Possible neighbors in k-th direction
%    Q = G(p+k);
%    % Index of points with interior neighbors
%    q = find(Q);
%    % Connect interior points to neighbors with -1's.
%    i = [i; G(p(q))];
%    j = [j; Q(q)];
%    s = [s; -ones(length(q),1)];
% end
% D = sparse(i,j,s);
